<a href="https://colab.research.google.com/github/hxxn05/ABCD-A/blob/main/20240516.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [10]:
## Pooling example
input_example = torch.tensor([[[0, 1, 2],[3,4,5],[6,7,8]]])
print(input_example)
#max pooling
max_pooling_layer =nn.MaxPool2d(kernel_size = 2, stride = 1)
print(max_pooling_layer)
print(max_pooling_layer(input_example))
#average pooling
average_pooling_layer = torch.nn.AvgPool2d(kernel_size =2, stride = 1)
print(average_pooling_layer)
print(average_pooling_layer(input_example))


tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, ceil_mode=False)
tensor([[[4, 5],
         [7, 8]]])
AvgPool2d(kernel_size=2, stride=1, padding=0)
tensor([[[2, 3],
         [5, 6]]])


In [20]:
input_example = torch.tensor([[[12,20,30,0],[20,12,2,0],[0,70,5,2],]])
print(input_example)

max_pooling_layer = nn.MaxPool2d(kernel_size = 2, stride = 2)
print('\nmax pooling: \n', max_pooling_layer(input_example))

average_pooling_layer = torch.nn.AvgPool2d(kernel_size= 2, stride =2)
print('\naverage pooling:\n', average_pooling_layer(input_example))


tensor([[[12, 20, 30,  0],
         [20, 12,  2,  0],
         [ 0, 70,  5,  2]]])

max pooling: 
 tensor([[[20, 30]]])

average pooling:
 tensor([[[16,  8]]])


In [21]:
conv1 = nn.Conv2d(in_channels=1, out_channels= 32, kernel_size=3, padding=1)

print(conv1)

Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [24]:
conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)

print(conv2)

Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [28]:

out = torch.randn(1, 4096)


fc = nn.Linear(4096, 10)


out = fc(out)


print(out.shape)
print(out)


torch.Size([1, 10])
tensor([[-0.4372,  1.2019,  0.4155,  0.1123,  1.3727, -0.3513,  0.6098,  0.0514,
         -0.2181,  0.6425]], grad_fn=<AddmmBackward0>)
